shell.executable("/bin/bash")
shell.prefix("source ~/.bash_profile; ")
from os import path
from glob import glob
from collections import defaultdict

configfile: "config.yaml"

DATA = config["DATA"]
VIRAL_IDX = config["VIRAL_IDX"]
U6_IDX = config["U6_IDX"]
MRNA_IDX = config["MRNA_IDX"]
TRNA_IDX = config["TRNA_IDX"]
R18S_IDX = config["R18S_IDX"]
R28S_IDX = config["R28S_IDX"]
R5S_IDX = config["R5S_IDX"]
R58S_IDX = config["R58S_IDX"] 
CHROM_SIZES = config["CHROM_SIZES"]
ALL_IDX = config["ALL_IDX"]


SAMPLES = ["B6_mock_09", "B6_mock_012","B6_mock_9","B6_mock_12","B6_MHVV_9","B6_MHVV_12","B6_MHVS_9", "B6_MHVS_12", 
"B6_ns2_9","B6_ns2_12", "B6_nsp15_9","B6_nsp15_12", "IFNAR_mock_09", "IFNAR_mock_012","IFNAR_mock_9","IFNAR_mock_12", 
"IFNAR_MHVV_9", "IFNAR_MHVV_12", "IFNAR_MHVS_9","IFNAR_MHVS_12","IFNAR_ns2_9","IFNAR_ns2_12", "IFNAR_nsp15_9",
"IFNAR_nsp15_12", "RNaseL_mock_09","RNaseL_mock_012", "RNaseL_MHVS_9","RNaseL_MHVS_12","RNaseL_mock_9",
"RNaseL_mock_12", "RNaseL_MHVV_9","RNaseL_MHVV_12", "RNaseL_ns2_9", "RNaseL_ns2_12", "RNaseL_nsp15_9", "RNaseL_nsp15_12"] 


BG_NAMES = ["mhv" , "tRNA", "r18s" , "r28s" , "r5.8s" , "r5s" , "U6" , "mRNA"]


rule all:
 input:
   expand("results/split_bg/{bg_name}/{sample}.{bg_name}.bg",
     bg_name = BG_NAMES,
     sample = SAMPLES),
   expand("results/mhv/normalized_bg/{sample}.mhv.pos.normalized.bg",
     sample = SAMPLES),
   expand("results/mhv/normalized_bg/{sample}.mhv.neg.normalized.bg",
     sample = SAMPLES)

include: 'rules/align.snake'
include: 'rules/coverage.snake'
include: 'rules/normalize.snake'
include: 'rules/split_bedgraph.snake'








